import uuid
from decimal import Decimal
from datetime import datetime
from wheelshub.models import Deal

def get_car_data():
    car_data = [
        {
            "make": "Toyota",
            "model": "Corolla",
            "title": "Toyota Corolla - Great for Long Drives",
            "description": "Reliable and fuel-efficient, this Corolla has been perfect for road trips and city driving alike. Kept in excellent condition and drives smoothly.",
            "price": Decimal('11000.00'),
            "year": 2017,
            "mileage": 52000,
            "condition": "used",
            "fuel_type": "gasoline",
            "transmission": "manual",
            "body_type": "sedan",
            "engine_capacity": Decimal('1.8'),
            "location": "Umeå, Sweden",
            "image": "https://example.com/images/toyotaCorolla2.jpg",
        },
        {
            "make": "BMW",
            "model": "X5",
            "title": "BMW X5 - Powerful SUV",
            "description": "A great choice for those who want power and luxury combined. This BMW X5 is smooth, spacious, and has been maintained in excellent condition.",
            "price": Decimal('34000.00'),
            "year": 2018,
            "mileage": 45000,
            "condition": "certified",
            "fuel_type": "diesel",
            "transmission": "automatic",
            "body_type": "suv",
            "engine_capacity": Decimal('3.0'),
            "location": "Västerås, Sweden",
            "image": "https://example.com/images/bmwX5.jpg",
        },
        {
            "make": "Volkswagen",
            "model": "Passat",
            "title": "Volkswagen Passat - Family Friendly",
            "description": "Spacious and comfortable, this Passat has been our family car and it’s ideal for both city and highway driving. Great fuel efficiency and lots of space.",
            "price": Decimal('17000.00'),
            "year": 2016,
            "mileage": 67000,
            "condition": "used",
            "fuel_type": "diesel",
            "transmission": "manual",
            "body_type": "sedan",
            "engine_capacity": Decimal('2.0'),
            "location": "Linköping, Sweden",
            "image": "https://example.com/images/vwPassat.jpg",
        },
        {
            "make": "Mercedes",
            "model": "E-Class",
            "title": "Mercedes E-Class - Elegant and Powerful",
            "description": "Luxury and power combined in this E-Class. Drives like a dream and is perfect for those who want elegance in every ride.",
            "price": Decimal('30000.00'),
            "year": 2019,
            "mileage": 30000,
            "condition": "certified",
            "fuel_type": "gasoline",
            "transmission": "automatic",
            "body_type": "sedan",
            "engine_capacity": Decimal('2.0'),
            "location": "Norrköping, Sweden",
            "image": "https://example.com/images/mercedesEClass.jpg",
        },
        {
            "make": "Audi",
            "model": "Q7",
            "title": "Audi Q7 - Spacious and Luxurious SUV",
            "description": "This Audi Q7 has been wonderful for family trips with its spacious interior and smooth handling. It’s powerful and luxurious—ideal for long drives.",
            "price": Decimal('45000.00'),
            "year": 2017,
            "mileage": 70000,
            "condition": "used",
            "fuel_type": "diesel",
            "transmission": "automatic",
            "body_type": "suv",
            "engine_capacity": Decimal('3.0'),
            "location": "Helsingborg, Sweden",
            "image": "https://example.com/images/audiQ7.jpg",
        },
        {
            "make": "Honda",
            "model": "Accord",
            "title": "Honda Accord - Reliable and Comfortable",
            "description": "A comfortable, spacious car that's been a reliable part of our daily commute. Regularly serviced and runs perfectly.",
            "price": Decimal('15000.00'),
            "year": 2018,
            "mileage": 48000,
            "condition": "used",
            "fuel_type": "gasoline",
            "transmission": "manual",
            "body_type": "sedan",
            "engine_capacity": Decimal('1.6'),
            "location": "Jönköping, Sweden",
            "image": "https://example.com/images/hondaAccord.jpg",
        },
        {
            "make": "Ford",
            "model": "Mustang",
            "title": "Ford Mustang - Classic American Muscle",
            "description": "For those who love power and style. This Mustang turns heads and sounds incredible. Great condition, well-maintained, and a joy to drive.",
            "price": Decimal('38000.00'),
            "year": 2021,
            "mileage": 15000,
            "condition": "certified",
            "fuel_type": "gasoline",
            "transmission": "manual",
            "body_type": "coupe",
            "engine_capacity": Decimal('5.0'),
            "location": "Gothenburg, Sweden",
            "image": "https://example.com/images/fordMustang.jpg",
        },
        {
            "make": "Tesla",
            "model": "Model 3",
            "title": "Tesla Model 3 - Eco-Friendly and Powerful",
            "description": "Fast, silent, and eco-friendly. This Model 3 is fully electric and in perfect shape. Ideal for anyone looking to switch to an electric lifestyle.",
            "price": Decimal('55000.00'),
            "year": 2020,
            "mileage": 22000,
            "condition": "certified",
            "fuel_type": "electric",
            "transmission": "automatic",
            "body_type": "sedan",
            "engine_capacity": Decimal('0.0'),
            "location": "Stockholm, Sweden",
            "image": "https://example.com/images/teslaModel3.jpg",
        },
        {
            "make": "Hyundai",
            "model": "Tucson",
            "title": "Hyundai Tucson - Great for Families",
            "description": "A spacious SUV with excellent features and reliability. This Tucson is perfect for families and has been well cared for.",
            "price": Decimal('18000.00'),
            "year": 2016,
            "mileage": 75000,
            "condition": "used",
            "fuel_type": "diesel",
            "transmission": "automatic",
            "body_type": "suv",
            "engine_capacity": Decimal('2.0'),
            "location": "Luleå, Sweden",
            "image": "https://example.com/images/hyundaiTucson.jpg",
        },
        {
            "make": "Mazda",
            "model": "6",
            "title": "Mazda 6 - Comfortable Sedan with Great Mileage",
            "description": "This Mazda 6 is in great shape and offers fantastic mileage. Comfortable interior and reliable—an ideal commuter car.",
            "price": Decimal('14000.00'),
            "year": 2018,
            "mileage": 58000,
            "condition": "used",
            "fuel_type": "gasoline",
            "transmission": "manual",
            "body_type": "sedan",
            "engine_capacity": Decimal('2.0'),
            "location": "Örebro, Sweden",
            "image": "https://example.com/images/mazda6.jpg",
        }
    ]
    
    return car_data

def populate_database():
    car_listings = []
    for data in get_car_data():
        car_listing = Deal(
            id=uuid.uuid4(),
            seller=uuid.uuid4(),
            title=data["title"],
            description=data["description"],
            price=data["price"],
            make=data["make"],
            model=data["model"],
            year=data["year"],
            mileage=data["mileage"],
            condition=data["condition"],
            location=data["location"],
            fuel_type=data["fuel_type"],
            transmission=data["transmission"],
            body_type=data["body_type"],
            engine_capacity=data["engine_capacity"],
            image=data["image"],
            status="active",
            created_at=datetime.now()
        )
        car_listings.append(car_listing)
    
    # Bulk create the listings
    Deal.objects.bulk_create(car_listings)
