# Generated by Django 4.2.16 on 2024-11-11 14:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller', models.UUIDField()),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('condition', models.CharField(max_length=20)),
                ('location', models.TextField()),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('truck', 'Truck'), ('coupe', 'Coupe'), ('convertible', 'Convertible')], max_length=20)),
                ('engine_capacity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('image', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('pending', 'Pending'), ('closed', 'Closed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'deals',
            },
        ),
    ]
