# Generated by Django 4.2.16 on 2024-11-11 00:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wheelshub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('town_city', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('variant', models.CharField(max_length=50)),
                ('mileage', models.CharField(max_length=50)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'car_listings',
            },
        ),
    ]
