# Generated by Django 4.2.16 on 2024-11-12 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wheelshub', '0004_bid_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='bid',
            name='contact',
            field=models.CharField(default="123", max_length=15),
            preserve_default=False,
        ),
    ]
