# Generated by Django 4.2.16 on 2024-11-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheelshub', '0005_remove_bid_phone_number_bid_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
